title: Hossein Darvish
description: Stuff that I come across and find interesting.
author: Hossein Darvish
email: hossein.darvish@unisalento.it
#phone: (+39) 351-5835532
github: https://github.com/HDarvish
about: I am a Mechanical Engineer and an Artist.
disqus_shortname: programming
#google_analytics: UA-31048387-6
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/hossein.darvish.90"
    - icon: fa-twitter
      link: "https://twitter.com/dar__wish"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/darvish-hossein/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/HDarvish"

share:
  twitter_username: dar__wish
  # fb_appid: 1749788565247320
  # Let's find how we can make the repo private!

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Photos
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://hdarvish.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
